### ISSUE TITLE
I forgot to import IIngredient when adding inscriber recipes

### ISSUE THREAD

**Issue by wwwDayDream** [jaredlll08/AppliedEnergisticsTweaker#3]
Edit: Unknown if grinder recipes work, haven't attempted editing them. Will try now and update soon.

When using the provided recipe format, or any format shown below crafttweaker always throws this error.

`<recipetype:appliedenergistics2:inscriber>.addInscribeRecipe("inscriber_inscribe_test_bottom_input", <item:minecraft:glass>, <item:minecraft:stick>, [<item:minecraft:air>, <item:minecraft:stick>] as IIngredient[]);
`

Error:

[11:40:10.196][DONE][CLIENT][ERROR] ae2\inscriber.zs:5:0 ae2\inscriber.zs:5:0: No matching method found for addInscribeRecipe:
Parameter 3: cannot cast invalid[] to IIngredient[]?

**Comment by jaredlll08** [comment]
You need to import IIngredient at the top of your file.

https://docs.blamejared.com/1.16/en/vanilla/api/items/IIngredient/#importing-the-class

**Comment by wwwDayDream** [comment]
I feel dumb, thank you. Sorry for the useless issue

**Comment by jaredlll08** [comment]
No worries, I should make it clearer on the page.
